'use strict';
(()=>{
const $=id=>document.getElementById(id), peers=new Map(), audio=new Map();
let socket,stream,code='',owner='',ice=[],members=[],busy=false,muted=false,generation=0;
const msg=text=>$('message').textContent=text||'';
$('mic').append(lucide.createElement(lucide.Mic));
function request(event,data={}){return new Promise((resolve,reject)=>socket.timeout(10000).emit(event,data,(err,r)=>err?reject(Error('Сервер не ответил.')):r?.ok?resolve(r):reject(Error(r?.error||'Ошибка соединения.'))));}
function paint(){const ul=$('members');ul.replaceChildren();for(const member of members){const li=document.createElement('li'),name=document.createElement('span'),status=document.createElement('small');name.textContent=member.name+(member.id===socket?.id?' (вы)':'');status.textContent=member.muted?'Микрофон выключен':member.id===socket?.id?'Микрофон включён':peers.get(member.id)?.pc.connectionState==='connected'?'Подключён':'Соединение...';li.append(name,status);ul.append(li);}$('close').hidden=owner!==socket?.id;}
function removePeer(id){peers.get(id)?.pc.close();peers.delete(id);const el=audio.get(id);if(el){el.srcObject=null;el.remove();audio.delete(id);}}
function reset(){generation++;for(const id of [...peers.keys()])removePeer(id);stream?.getTracks().forEach(t=>t.stop());stream=null;code='';members=[];owner='';muted=false;$('room').hidden=true;$('entry').hidden=false;$('mic').setAttribute('aria-pressed','false');$('mic').title=$('mic').ariaLabel='Выключить микрофон';$('create').disabled=$('join').disabled=!socket?.connected;}
function peer(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection({iceServers:ice}),record={pc,queue:[],chain:Promise.resolve()};peers.set(id,record);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>{if(e.candidate)request('signal',{to:id,signal:{type:'candidate',candidate:e.candidate.toJSON()}}).catch(e=>msg(e.message));};pc.ontrack=e=>{let el=audio.get(id);if(!el){el=document.createElement('audio');el.autoplay=true;document.body.append(el);audio.set(id,el);}el.srcObject=e.streams[0]||new MediaStream([e.track]);el.volume=Number($('volume').value)/100;el.play().catch(()=>msg('Нажмите кнопку микрофона или громкости, чтобы включить звук браузера.'));};pc.onconnectionstatechange=()=>{paint();if(pc.connectionState==='failed')msg('Не удалось установить аудиосоединение. Выйдите и присоединитесь снова.');};return record;}
async function signal(data){if(!stream||!code)return;const record=peer(data.from),pc=record.pc;record.chain=record.chain.then(async()=>{const s=data.signal;if(s.type==='candidate'){if(pc.remoteDescription)await pc.addIceCandidate(s.candidate);else if(record.queue.length<100)record.queue.push(s.candidate);return;}await pc.setRemoteDescription({type:s.type,sdp:s.sdp});for(const c of record.queue.splice(0))await pc.addIceCandidate(c);if(s.type==='offer'){await pc.setLocalDescription(await pc.createAnswer());await request('signal',{to:data.from,signal:{type:'answer',sdp:pc.localDescription.sdp}});}}).catch(e=>msg('Ошибка звука: '+e.message));}
function parseCode(value){value=value.trim();if(/^https?:\/\//.test(value)){const url=new URL(value);if(url.origin!==location.origin||url.pathname!=='/foleam-voice.html')throw Error('Нужна ссылка Foleam Voice.');value=url.hash.slice(1);}value=value.toUpperCase();if(!/^[A-F0-9]{12}$/.test(value))throw Error('Проверьте 12-значный код лобби.');return value;}
async function join(create){if(busy)return;busy=true;$('create').disabled=$('join').disabled=true;const attempt=++generation;try{const wanted=create?'':parseCode($('code').value);msg('Запрашиваем микрофон...');const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(generation!==attempt||!socket.connected){media.getTracks().forEach(t=>t.stop());return;}stream=media;const result=await request('join',{create,code:wanted});if(generation!==attempt){await request('leave');return;}code=result.code;owner=result.owner;ice=result.iceServers;location.hash=code;$('entry').hidden=true;$('room').hidden=false;$('room-code').textContent=code;paint();msg('');for(const p of result.peers){const {pc}=peer(p.id);await pc.setLocalDescription(await pc.createOffer());await request('signal',{to:p.id,signal:{type:'offer',sdp:pc.localDescription.sdp}});}}catch(e){if(code)await request('leave').catch(()=>{});reset();msg(e.name==='NotAllowedError'?'Разрешите доступ к микрофону для голосового чата.':e.message);}finally{busy=false;$('create').disabled=$('join').disabled=!socket?.connected;}}
$('create').onclick=()=>join(true);$('join-form').onsubmit=e=>{e.preventDefault();join(false);};
$('mic').onclick=()=>{muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);$('mic').setAttribute('aria-pressed',String(muted));$('mic').title=$('mic').ariaLabel=muted?'Включить микрофон':'Выключить микрофон';request('mute',{muted}).catch(e=>msg(e.message));for(const el of audio.values())el.play().catch(()=>{});};
$('volume').oninput=()=>{$('volume-value').textContent=$('volume').value+'%';for(const el of audio.values()){el.volume=Number($('volume').value)/100;el.play().catch(()=>{});}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+'/foleam-voice.html#'+code);msg('Ссылка скопирована.');}catch{msg('Приглашение: '+location.origin+'/foleam-voice.html#'+code);}};
$('leave').onclick=async()=>{await request('leave').catch(()=>{});reset();msg('Вы вышли из лобби.');};$('close').onclick=async()=>{if(confirm('Закрыть лобби для всех участников?'))await request('close').catch(e=>msg(e.message));};
addEventListener('pagehide',()=>{reset();socket?.disconnect();});
if(location.hash)$('code').value=location.hash.slice(1);
(async()=>{try{const response=await fetch('/api/foleam-voice/session',{cache:'no-store'});if(!response.ok){$('login').hidden=false;throw Error(response.status===401?'Войдите в Mailan1, затем вернитесь к приглашению.':'Голосовой сервис пока недоступен.');}const data=await response.json();$('identity').textContent=data.user.name;ice=data.iceServers;socket=io('/foleam-voice',{auth:{csrf:data.csrf},transports:['websocket','polling'],reconnection:true});socket.on('connect',()=>{$('connection').textContent='В сети';$('create').disabled=$('join').disabled=false;});socket.on('disconnect',()=>{reset();$('connection').textContent='Соединение потеряно';msg('Связь прервана. После подключения войдите в лобби снова.');});socket.on('connect_error',e=>msg(e.message));socket.on('roster',data=>{members=data.members;owner=data.owner;for(const id of peers.keys())if(!members.some(m=>m.id===id))removePeer(id);paint();});socket.on('signal',signal);socket.on('ended',reason=>{reset();msg(reason);});if(!data.relayConfigured)msg('Ретранслятор не настроен: соединение между разными сетями может не работать.');}catch(e){msg(e.message);}})();
})();
